[package]

name = "pistoncore-sdl2_window"
version = "0.0.11"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"]
keywords = ["sdl2", "window", "piston"]
description = "A SDL2 back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/sdl2_window.git"
homepage = "https://github.com/pistondevelopers/sdl2_window"

[lib]

name = "sdl2_window"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
#version = "0.2.0"

[dependencies.piston]
git = "https://github.com/pistondevelopers/piston"
#version = "0.1.0"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"
#version = "0.0.6"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
#version = "0.0.12"

[dependencies]
num = "0.1.21"
