[package]

name = "pistoncore-sdl2_window"
version = "0.0.15"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "Tony Aldridge <tony@angry-lawyer.com>"]
keywords = ["sdl2", "window", "piston"]
description = "A SDL2 back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/sdl2_window.git"
homepage = "https://github.com/pistondevelopers/sdl2_window"

[lib]

name = "sdl2_window"

[dependencies]
num = "0.1.24"
sdl2 = "0.4"
piston = "0.1.3"
shader_version = "0.0.6"
gl = "0.0.12"
